#include "Board.hpp"
#include <memory>

Board::Board()
{
    fields.push_back(std::make_unique<FieldStart>());
    fields.push_back(std::make_unique<FieldEmpty>());
    fields.push_back(std::make_unique<FieldEmpty>());
    fields.push_back(std::make_unique<FieldReward>());
    fields.push_back(std::make_unique<FieldPenalty>());
    fields.push_back(std::make_unique<FieldEmpty>());
    fields.push_back(std::make_unique<FieldEmpty>());
    fields.push_back(std::make_unique<FieldEmpty>());
    fields.push_back(std::make_unique<FieldPenalty>());
    fields.push_back(std::make_unique<FieldPenalty>());
    fields.push_back(std::make_unique<FieldReward>());
    fields.push_back(std::make_unique<FieldReward>());
    fields.push_back(std::make_unique<FieldEmpty>());
    fields.push_back(std::make_unique<FieldEmpty>());
    fields.push_back(std::make_unique<FieldEmpty>());
    fields.push_back(std::make_unique<FieldEmpty>());
    fields.push_back(std::make_unique<FieldEmpty>());
    fields.push_back(std::make_unique<FieldReward>());
    fields.push_back(std::make_unique<FieldPenalty>());
    fields.push_back(std::make_unique<FieldEmpty>());
    fields.push_back(std::make_unique<FieldEmpty>());
    fields.push_back(std::make_unique<FieldEmpty>());
    fields.push_back(std::make_unique<FieldPenalty>());
    fields.push_back(std::make_unique<FieldPenalty>());
    fields.push_back(std::make_unique<FieldReward>());
    fields.push_back(std::make_unique<FieldReward>());
    fields.push_back(std::make_unique<FieldEmpty>());
    fields.push_back(std::make_unique<FieldEmpty>());
    fields.push_back(std::make_unique<FieldEmpty>());
    fields.push_back(std::make_unique<FieldEmpty>());
    fields.push_back(std::make_unique<FieldEmpty>());
    fields.push_back(std::make_unique<FieldReward>());
    fields.push_back(std::make_unique<FieldPenalty>());
    fields.push_back(std::make_unique<FieldEmpty>());
    fields.push_back(std::make_unique<FieldEmpty>());
    fields.push_back(std::make_unique<FieldEmpty>());
    fields.push_back(std::make_unique<FieldPenalty>());
    fields.push_back(std::make_unique<FieldPenalty>());
    fields.push_back(std::make_unique<FieldReward>());
    fields.push_back(std::make_unique<FieldReward>());
}